baseURL: 'https://marcpabst.github.io/hugo-maps/'
languageCode: 'en-gb'
title: 'Hugo Maps Demo'

params:
  hugo-maps:
      default:
        sources: 
           openmaptiles:
             type: vector
             url: https://api.maptiler.com/tiles/v3/tiles.json?key=143k20pEdcyOeBepEEnR
        height: 500px
      map_3d:
        style: maptiler-3d
        center: [-0.127758, 51.507351]
        wm-bounding-box: [0.499265, 0.3329205529428414, 0.5001916666666667, 0.33214313777934357]
        tilesMinZoom: 0
        tilesMaxZoom: 14
        minZoom: 4
        maxZoom: 20
        zoom: 15
        pitch: 30
        antialias: true
        markers:
          - location: [-0.127972, 51.507722, ]
            text: "Nelson's Column"
      theme_map:
        zoom: 15
        interactive: false
        center: [-0.127758, 51.507351]
        navigationControl: false
      os_theme_map:
        zoom: 15
        center: [-0.127758, 51.507351]
        navigationControl: false
        setFeatureState:
          - feature:
              id: 4372002
              source: openmaptiles
              sourceLayer: building
            state: 
              active: true
        sources: 
           composite:
             type: vector
             url: https://s3-eu-west-1.amazonaws.com/tiles.os.uk/v2/data/vector/open-zoomstack/config.json
            
      new_york_map:
        center: [-74.005833, 40.712778]
      map2:
        type: remote
        style: toner

module:
  replacements: "github.com/marcpabst/hugo-maps -> ../.."
  imports:
   - # theme
     path: "github.com/alex-shpak/hugo-book"
   - # maps
     path: "github.com/marcpabst/hugo-maps"